name: Check CRAN status

on:
  schedule:
    # Runs daily at 4:00 PM UTC (9:00 AM PST)
    - cron: '0 16 * * *'
  # allows for manually running of the check
  workflow_dispatch:

jobs:
  check_cran_status:
    runs-on: ubuntu-latest

    steps:
      - name: Get CRAN checks - hoopR
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: hoopR
      - name: Get CRAN checks - wehoop
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: wehoop
      - name: Get CRAN checks - fastRhockey
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: fastRhockey
      - name: Get CRAN checks - baseballr
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: baseballr
      - name: Get CRAN checks - worldfootballR
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: worldfootballR
      - name: Get CRAN checks - sportyR
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: sportyR
      - name: Get CRAN checks - oddsapiR
        uses: ricochet-rs/cran-checks/check-pkg@main
        with:
          pkg: oddsapiR
